server:
    port: 8081

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true

spring:
    application:
        name: gateway-service
    cloud:
        gateway:
            routes: 
            - id: author-service
              uri: lb://author-service
              predicates:
                - Path=/author/**
            - id: item-service
              uri: lb://item-service
              predicates:
                - Path=/item/**
            discovery:
              locator:
                lower-case-service-id: true
                enabled: true